- project:
    check:
      queue: sesheta
      jobs:
        - linters
    gate:
      queue: sesheta
      jobs:
        - linters
    post:
      jobs:
        - trigger-build:
            vars:
              webhook_url: "https://url.corp.redhat.com/aicoe-prod-bots-kebechet-webhooks-trigger"
    kebechet-auto-gate:
      jobs:
        - linters
