- project:
    check:
      queue: sesheta
      jobs:
        - linters
    gate:
      queue: sesheta
      jobs:
        - linters
    post:
      jobs:
        - trigger-build:
            vars:
              webhook_url: "https://paas.upshift.redhat.com/oapi/v1/namespaces/aicoe-prod-bots/buildconfigs/kebechet-webhooks/webhooks/_HeYM4WPbHESGb7m1czo/generic"
    kebechet-auto-gate:
      jobs:
        - linters
