organization: thoth-station
repositories:
  - core
  - user-api
  - common
  - package-releases-job
  - graph-refresh-job
  - result-api
  - solver
  - graph-sync-job
  - cleanup-job
  - package-extract
  - adviser
  - analyzer
  - build-analysers
  - dependency-monkey
  - notebooks
  - jupyter-notebook
  - lab
  - naming-service
  - misc
defaultLabels:
  - name: 'bot'
    color: '698b69'
  - name: 'approved'
    color: '00cc00'
  - name: 'do-not-merge'
    color: 'cc0000'
  - name: 'do-not-merge/work-in-progress'
    color: 'cc0000'
  - name: 'work-in-progress'
    color: 'cc0000'
  - name: 'needs-rebase'
    color: 'cc0000'
  - name: 'component/metrics'
    color: '0052cc'
  - name: 'component/solver'
    color: '0052cc'
  - name: 'component/analyser'
    color: '0052cc'
  - name: 'component/bots'
    color: '0052cc'
  - name: 'component/logging'
    color: '0052cc'
  - name: 'component/monitoring'
    color: '0052cc'
  - name: 'component/notebook'
    color: '0052cc'