apiVersion: v1
kind: Template
labels:
  template: sesheta-buildconfig
  thoth: 0.1.0
metadata:
  name: sesheta-buildconfig
  annotations:
    description: >
      This is sesheta CronJob BuildConfig, this template is meant to be used by Bots,
      but could also be used by humans...
    openshift.io/display-name: sesheta BuildConfig
    version: 2.0.0-dev
    tags: poc,thoth,ai-stacks,sesheta
    template.openshift.io/documentation-url: https://github.com/thoth-station/sesheta/
    template.openshift.io/long-description: This is sesheta used for automatic package releases and updates.
    template.openshift.io/provider-display-name: Red Hat, Inc.

objects:
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      labels:
        app: sesheta
      name: sesheta-webhooks
    spec:
      failedBuildsHistoryLimit: 5
      output:
        to:
          kind: ImageStreamTag
          name: sesheta-webhooks:latest
      resources:
        limits:
          cpu: "2"
          memory: 2Gi
        requests:
          cpu: "1"
          memory: 768Mi
      source:
        type: Git
        git:
          ref: ${GITHUB_REF}
          uri: ${GITHUB_URL}
        contextDir: ${GITHUB_CONTEXT_DIR}
      strategy:
        type: Source
        sourceStrategy:
          env:
            - name: ENABLE_PIPENV
              value: "1"
          from:
            kind: ImageStreamTag
            name: python-36-centos7:latest
      successfulBuildsHistoryLimit: 2
      triggers:
        - type: ImageChange
          imageChange: {}
        - type: ConfigChange

parameters:
  - description: Git repository for Thoth's sesheta
    displayName: Thoth sesheta git repository
    required: true
    name: GITHUB_URL
    value: 'https://github.com/AICoE/sesheta'

  - description: Git reference for Thoth's sesheta
    displayName: Thoth sesheta git reference
    required: true
    name: GITHUB_REF
    value: 'master'

  - description: Context directory
    displayName: Context directory
    required: true
    name: GITHUB_CONTEXT_DIR
    value: ''

  - description: Tag of the output ImageStream the resulting container image should go to
    displayName: ImageStream Tag
    required: true
    name: IMAGE_STREAM_TAG
    value: 'latest'
