apiVersion: v1
kind: Template
metadata:
  name: sesheta-configmap
  labels:
    template: sesheta-configmap
    thoth: 0.1.0
    app: sesheta
    component: configmap
  annotations:
    description: >
      This is sesheta ConfigMap, this template is meant to be used by Bots,
      but could also be used by humans...
    openshift.io/display-name: sesheta BuildConfig
    version: 2.3.3
    tags: thoth,ai-stacks,aistacks,sesheta
    template.openshift.io/documentation-url: https://github.com/thoth-station/sesheta/
    template.openshift.io/long-description: This is sesheta used for automatic package releases and updates.
    template.openshift.io/provider-display-name: Red Hat, Inc.

parameters:
  - description: Sesheta verbose mode.
    displayName: Sesheta verbose
    required: true
    name: SESHETA_VERBOSE
    value: "1"

  - description: Google chat room space.
    displayName: SESHETA_SCRUM_SPACE
    required: true
    name: SESHETA_SCRUM_SPACE

  - description: scrum message for the thread.
    displayName: SESHETA_SCRUM_MESSAGE
    required: true
    name: SESHETA_SCRUM_MESSAGE
    value: "☎️ the scrum is due in one minute..."

  - description: Bluejeans scrum url.
    displayName: SESHETA_SCRUM_URL
    required: true
    name: SESHETA_SCRUM_URL

  - description: Scrum google chat threadKey.
    displayName: SCRUM_THREAD_KEY
    required: true
    name: SCRUM_THREAD_KEY

  - description: Users Inivited for the Scrum stand call.
    displayName: USERS_INVITED
    required: true
    name: USERS_INVITED

objects:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: sesheta-configmap
      labels:
        app: sesheta
    data:
      sesheta-verbose: ${SESHETA_VERBOSE}
      scrum-space: ${SESHETA_SCRUM_SPACE}
      scrum-message: ${SESHETA_SCRUM_MESSAGE}
      scrum-url: ${SESHETA_SCRUM_URL}
      scrum-threadkey: ${SCRUM_THREAD_KEY}
      users-invited: ${USERS_INVITED}
